/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB 301-PC09
 */
public class Menuu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menuu() {
        initComponents();
        sp1.setEnabled(false);
        sp2.setEnabled(false);
        sp3.setEnabled(false);
        sp4.setEnabled(false);
        sp5.setEnabled(false);
        sp6.setEnabled(false);
        sp7.setEnabled(false);
        sp8.setEnabled(false);
        sp9.setEnabled(false);
        sp10.setEnabled(false);
        sp11.setEnabled(false);
        sp12.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        sp1 = new javax.swing.JSpinner();
        sp2 = new javax.swing.JSpinner();
        sp3 = new javax.swing.JSpinner();
        sp4 = new javax.swing.JSpinner();
        sp5 = new javax.swing.JSpinner();
        sp6 = new javax.swing.JSpinner();
        sp7 = new javax.swing.JSpinner();
        sp8 = new javax.swing.JSpinner();
        sp9 = new javax.swing.JSpinner();
        sp10 = new javax.swing.JSpinner();
        sp11 = new javax.swing.JSpinner();
        sp12 = new javax.swing.JSpinner();
        cheBox1 = new javax.swing.JCheckBox();
        cheBox2 = new javax.swing.JCheckBox();
        cheBox3 = new javax.swing.JCheckBox();
        cheBox4 = new javax.swing.JCheckBox();
        cheBox5 = new javax.swing.JCheckBox();
        cheBox7 = new javax.swing.JCheckBox();
        cheBox8 = new javax.swing.JCheckBox();
        cheBox6 = new javax.swing.JCheckBox();
        cheBox9 = new javax.swing.JCheckBox();
        cheBox12 = new javax.swing.JCheckBox();
        cheBox10 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cheBox11 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel1.setBackground(new java.awt.Color(255, 255, 255));
        panel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENÚ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 0, 48))); // NOI18N
        panel1.setForeground(new java.awt.Color(153, 153, 255));

        sp1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp1.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp2.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp3.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp4.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp5.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp6.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp7.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp8.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp9.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp10.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp11.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp11.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        sp12.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        sp12.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        cheBox1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox1.setText("Hamburguesa 1.........................$200.00");
        cheBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox1ActionPerformed(evt);
            }
        });

        cheBox2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox2.setText("Hamburguesa 2.........................$200.00");
        cheBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox2ActionPerformed(evt);
            }
        });

        cheBox3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox3.setText("Hamburguesa 3.........................$200.00");
        cheBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox3ActionPerformed(evt);
            }
        });

        cheBox4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox4.setText("Hot Dog's 1...............................$200.00");
        cheBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox4ActionPerformed(evt);
            }
        });

        cheBox5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox5.setText("Hot Dog's 2...............................$200.00");
        cheBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox5ActionPerformed(evt);
            }
        });

        cheBox7.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox7.setText("Bebida 2.....................................$200.00");
        cheBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox7ActionPerformed(evt);
            }
        });

        cheBox8.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox8.setText("Bebida 3.....................................$200.00");
        cheBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox8ActionPerformed(evt);
            }
        });

        cheBox6.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox6.setText("Bebida 1.....................................$200.00");
        cheBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox6ActionPerformed(evt);
            }
        });

        cheBox9.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox9.setText("Bebida 4.....................................$200.00");
        cheBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox9ActionPerformed(evt);
            }
        });

        cheBox12.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox12.setText("Pastel 3.....................................$200.00");
        cheBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox12ActionPerformed(evt);
            }
        });

        cheBox10.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox10.setText("Pastel 1.....................................$200.00");
        cheBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox10ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel1.setText("Entradas:");

        jLabel2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel2.setText("Bebidas:");

        jLabel3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        jLabel3.setText("Postres:");

        cheBox11.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        cheBox11.setText("Pastel 2.....................................$200.00");
        cheBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cheBox11ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Sylfaen", 0, 16)); // NOI18N
        jLabel4.setText("Todas las entradas se les incluira una orden de papas a la francesa");

        jLabel5.setFont(new java.awt.Font("Sylfaen", 0, 15)); // NOI18N
        jLabel5.setText("Cantidad a ordenar");

        jButton1.setFont(new java.awt.Font("Sylfaen", 0, 17)); // NOI18N
        jButton1.setText("Confirmar orden");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel1Layout.createSequentialGroup()
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cheBox12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cheBox10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cheBox11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(sp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sp12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(panel1Layout.createSequentialGroup()
                            .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addGroup(panel1Layout.createSequentialGroup()
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cheBox6)
                                            .addComponent(cheBox7, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(cheBox8)
                                        .addComponent(cheBox9, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addGap(18, 18, 18)
                                    .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(sp6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sp7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sp8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(sp9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(160, 160, 160))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(31, 31, 31)
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5))
                            .addGroup(panel1Layout.createSequentialGroup()
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cheBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cheBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cheBox4, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cheBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(panel1Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(cheBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sp1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(13, 13, 13)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cheBox10)
                    .addComponent(sp10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox11))
                .addGap(12, 12, 12)
                .addGroup(panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sp12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cheBox12))
                .addContainerGap(48, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cheBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox1ActionPerformed
        if (cheBox1.isSelected()) {
            sp1.setEnabled(true);
        } else {
            sp1.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox1ActionPerformed

    private void cheBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox2ActionPerformed
        if (cheBox2.isSelected()) {
            sp2.setEnabled(true);
        } else {
            sp2.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox2ActionPerformed

    private void cheBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox3ActionPerformed
        if (cheBox3.isSelected()) {
            sp3.setEnabled(true);
        } else {
            sp3.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox3ActionPerformed

    private void cheBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox4ActionPerformed
        if (cheBox4.isSelected()) {
            sp4.setEnabled(true);
        } else {
            sp4.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox4ActionPerformed

    private void cheBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox5ActionPerformed
        if (cheBox5.isSelected()) {
            sp5.setEnabled(true);
        } else {
            sp5.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox5ActionPerformed

    private void cheBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox7ActionPerformed
        if (cheBox7.isSelected()) {
            sp7.setEnabled(true);
        } else {
            sp7.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox7ActionPerformed

    private void cheBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox8ActionPerformed
        if (cheBox8.isSelected()) {
            sp8.setEnabled(true);
        } else {
            sp8.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox8ActionPerformed

    private void cheBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox6ActionPerformed
        if (cheBox6.isSelected()) {
            sp6.setEnabled(true);
        } else {
            sp6.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox6ActionPerformed

    private void cheBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox9ActionPerformed
        if (cheBox9.isSelected()) {
            sp9.setEnabled(true);
        } else {
            sp9.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox9ActionPerformed

    private void cheBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox12ActionPerformed
        if (cheBox12.isSelected()) {
            sp12.setEnabled(true);
        } else {
            sp12.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox12ActionPerformed

    private void cheBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox10ActionPerformed
        if (cheBox10.isSelected()) {
            sp10.setEnabled(true);
        } else {
            sp10.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox10ActionPerformed

    private void cheBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cheBox11ActionPerformed
        if (cheBox11.isSelected()) {
            sp11.setEnabled(true);
        } else {
            sp11.setEnabled(false);
        }
    }//GEN-LAST:event_cheBox11ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AlgoMas hoja5 = new  AlgoMas();
        hoja5.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cheBox1;
    private javax.swing.JCheckBox cheBox10;
    private javax.swing.JCheckBox cheBox11;
    private javax.swing.JCheckBox cheBox12;
    private javax.swing.JCheckBox cheBox2;
    private javax.swing.JCheckBox cheBox3;
    private javax.swing.JCheckBox cheBox4;
    private javax.swing.JCheckBox cheBox5;
    private javax.swing.JCheckBox cheBox6;
    private javax.swing.JCheckBox cheBox7;
    private javax.swing.JCheckBox cheBox8;
    private javax.swing.JCheckBox cheBox9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel panel1;
    private javax.swing.JSpinner sp1;
    private javax.swing.JSpinner sp10;
    private javax.swing.JSpinner sp11;
    private javax.swing.JSpinner sp12;
    private javax.swing.JSpinner sp2;
    private javax.swing.JSpinner sp3;
    private javax.swing.JSpinner sp4;
    private javax.swing.JSpinner sp5;
    private javax.swing.JSpinner sp6;
    private javax.swing.JSpinner sp7;
    private javax.swing.JSpinner sp8;
    private javax.swing.JSpinner sp9;
    // End of variables declaration//GEN-END:variables
}
