/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author LAB 301-PC09
 */
public class Menuu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menuu() {
        initComponents();
        Hambur1.setEnabled(false);
        Hambur2.setEnabled(false);
        Hambur3.setEnabled(false);
        Hambur4.setEnabled(false);
        Hambur5.setEnabled(false);
        hot1.setEnabled(false);
        hot2.setEnabled(false);
        hot3.setEnabled(false);
        hot4.setEnabled(false);
        hot5.setEnabled(false);
        Piz1.setEnabled(false);
        Piz2.setEnabled(false);
        Piz3.setEnabled(false);
        Piz4.setEnabled(false);
        Piz5.setEnabled(false);
        Ali1.setEnabled(false);
        Ali2.setEnabled(false);
        Ali3.setEnabled(false);
        Ali4.setEnabled(false);
        Ali5.setEnabled(false);
        Bebi1.setEnabled(false);
        Bebi2.setEnabled(false);
        Bebi3.setEnabled(false);
        Bebi4.setEnabled(false);
        Bebi5.setEnabled(false);
        Postre1.setEnabled(false);
        Postre2.setEnabled(false);
        Postre3.setEnabled(false);
        Postre4.setEnabled(false);
        Postre5.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        Hambur1 = new javax.swing.JTextField();
        Hambur2 = new javax.swing.JTextField();
        Hambur3 = new javax.swing.JTextField();
        Hambur4 = new javax.swing.JTextField();
        Hambur5 = new javax.swing.JTextField();
        h1 = new javax.swing.JCheckBox();
        h2 = new javax.swing.JCheckBox();
        h3 = new javax.swing.JCheckBox();
        h4 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        h5 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ho1 = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        ho2 = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        ho3 = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        ho4 = new javax.swing.JCheckBox();
        ho5 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        hot5 = new javax.swing.JTextField();
        hot4 = new javax.swing.JTextField();
        hot3 = new javax.swing.JTextField();
        hot2 = new javax.swing.JTextField();
        hot1 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        P1 = new javax.swing.JCheckBox();
        jLabel11 = new javax.swing.JLabel();
        P2 = new javax.swing.JCheckBox();
        jLabel12 = new javax.swing.JLabel();
        P3 = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        P4 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        P5 = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        Piz1 = new javax.swing.JTextField();
        Piz2 = new javax.swing.JTextField();
        Piz3 = new javax.swing.JTextField();
        Piz4 = new javax.swing.JTextField();
        Piz5 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        A1 = new javax.swing.JCheckBox();
        jLabel16 = new javax.swing.JLabel();
        A2 = new javax.swing.JCheckBox();
        jLabel17 = new javax.swing.JLabel();
        A3 = new javax.swing.JCheckBox();
        jLabel18 = new javax.swing.JLabel();
        A4 = new javax.swing.JCheckBox();
        jLabel19 = new javax.swing.JLabel();
        A5 = new javax.swing.JCheckBox();
        jLabel20 = new javax.swing.JLabel();
        Ali1 = new javax.swing.JTextField();
        Ali2 = new javax.swing.JTextField();
        Ali3 = new javax.swing.JTextField();
        Ali4 = new javax.swing.JTextField();
        Ali5 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        B1 = new javax.swing.JCheckBox();
        jLabel21 = new javax.swing.JLabel();
        B2 = new javax.swing.JCheckBox();
        jLabel22 = new javax.swing.JLabel();
        B3 = new javax.swing.JCheckBox();
        jLabel23 = new javax.swing.JLabel();
        B4 = new javax.swing.JCheckBox();
        B5 = new javax.swing.JCheckBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Bebi1 = new javax.swing.JTextField();
        Bebi2 = new javax.swing.JTextField();
        Bebi3 = new javax.swing.JTextField();
        Bebi4 = new javax.swing.JTextField();
        Bebi5 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        Ps1 = new javax.swing.JCheckBox();
        Ps2 = new javax.swing.JCheckBox();
        jLabel27 = new javax.swing.JLabel();
        Ps3 = new javax.swing.JCheckBox();
        jLabel28 = new javax.swing.JLabel();
        Ps4 = new javax.swing.JCheckBox();
        jLabel29 = new javax.swing.JLabel();
        Ps5 = new javax.swing.JCheckBox();
        jLabel30 = new javax.swing.JLabel();
        Postre1 = new javax.swing.JTextField();
        Postre2 = new javax.swing.JTextField();
        Postre3 = new javax.swing.JTextField();
        Postre4 = new javax.swing.JTextField();
        Postre5 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "MENU", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Sylfaen", 0, 24))); // NOI18N

        Hambur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hambur1ActionPerformed(evt);
            }
        });
        Hambur1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Hambur1KeyTyped(evt);
            }
        });

        Hambur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hambur2ActionPerformed(evt);
            }
        });
        Hambur2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Hambur2KeyTyped(evt);
            }
        });

        Hambur3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Hambur3KeyTyped(evt);
            }
        });

        Hambur4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Hambur4KeyTyped(evt);
            }
        });

        Hambur5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Hambur5ActionPerformed(evt);
            }
        });
        Hambur5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Hambur5KeyTyped(evt);
            }
        });

        h1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        h1.setText("Hamburguesa Clásica");
        h1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h1ActionPerformed(evt);
            }
        });

        h2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        h2.setText("Hamburguesa BBQ");
        h2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h2ActionPerformed(evt);
            }
        });

        h3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        h3.setText("Hamburguesa Tex-Mex");
        h3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h3ActionPerformed(evt);
            }
        });

        h4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        h4.setText("Hamburguesa de pollo crujiente");
        h4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Pan, carne de res, lechuga, jitomate, cebolla, mayonesa, mostaza y kétchup");

        h5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        h5.setText("HamburguesaVeggie");
        h5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                h5ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel2.setText("Carne de res, tocino, queso cheddar, cebolla caramelizada, salsa BBQ, pan brioche");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel3.setText("Carne de res, guacamole, jalapeños, queso americano, lechuga y chipotle");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel4.setText("Pechuga empanizada, mayonesa, col morada, pepinillos, pan ajonjolí");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel5.setText("Hamburguesa de lentejas o garbanzos, lechuga, jitomate, aguacate, hummus, pan integral");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(h1)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(h2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(142, 142, 142))
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(h3)
                                            .addComponent(h4)
                                            .addComponent(h5)
                                            .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(21, 21, 21)
                                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel5))))
                                        .addGap(0, 34, Short.MAX_VALUE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(Hambur4, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Hambur5, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Hambur3, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(Hambur1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Hambur2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(h1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(23, 23, 23)
                        .addComponent(h2)
                        .addGap(4, 4, 4)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(h3)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(h4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addGap(29, 29, 29)
                        .addComponent(h5))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(Hambur1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(Hambur2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(Hambur3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(Hambur4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(Hambur5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Hamburguesas", jPanel4);

        ho1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ho1.setText("Hot Dog Clásico ");
        ho1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ho1ActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel6.setText("Salchicha, pan, kétchup, mostaza y cebolla");

        ho2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ho2.setText("Chili Dog ");
        ho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ho2ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel7.setText("Salchicha, pan, chili con carne, queso rallado, cebolla");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel8.setText("Salchicha envuelta en tocino, queso amarillo, mayonesa, jalapeños");

        ho3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ho3.setText("Hot Dog con Tocino");
        ho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ho3ActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel9.setText("Salchicha de res, tocino, jitomate, cebolla, frijoles, jalapeños, mayonesa, pan bolillo");

        ho4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ho4.setText("Hot Dog Estilo Sonora ");
        ho4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ho4ActionPerformed(evt);
            }
        });

        ho5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        ho5.setText("Hot Dog Vegano ");
        ho5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ho5ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel10.setText("Salchicha vegetal, pan integral, aguacate, tomate, mostaza dijon");

        hot5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hot5KeyTyped(evt);
            }
        });

        hot4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hot4KeyTyped(evt);
            }
        });

        hot3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hot3KeyTyped(evt);
            }
        });

        hot2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hot2KeyTyped(evt);
            }
        });

        hot1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                hot1KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ho3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hot3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ho4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hot4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ho5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hot5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(0, 180, Short.MAX_VALUE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(ho2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(hot2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(ho1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hot1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ho1)
                    .addComponent(hot1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(20, 20, 20)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ho2)
                    .addComponent(hot2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ho3)
                    .addComponent(hot3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ho4)
                    .addComponent(hot4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ho5)
                    .addComponent(hot5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addGap(36, 36, 36))
        );

        jTabbedPane2.addTab("Hot Dogs", jPanel5);

        P1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        P1.setText("Pizza Margarita ");
        P1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel11.setText("Salsa de tomate, queso mozzarella, albahaca");

        P2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        P2.setText("Pizza Pepperoni ");
        P2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P2ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel12.setText("Salsa, queso, pepperoni");

        P3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        P3.setText("Pizza Hawaiana ");
        P3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P3ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel13.setText("Jamón, piña, queso");

        P4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        P4.setText("Pizza de Carnes Frías ");
        P4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P4ActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel14.setText("Chorizo, jamón, salami, queso");

        P5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        P5.setText("Pizza Vegetariana ");
        P5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                P5ActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel15.setText("Champiñones, pimientos, cebolla, aceitunas, queso");

        Piz1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Piz1KeyTyped(evt);
            }
        });

        Piz2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Piz2KeyTyped(evt);
            }
        });

        Piz3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Piz3KeyTyped(evt);
            }
        });

        Piz4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Piz4KeyTyped(evt);
            }
        });

        Piz5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Piz5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(P1)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(P2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(P3)
                            .addComponent(P4)
                            .addComponent(P5)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel15)))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel11)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Piz1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Piz2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Piz3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Piz4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Piz5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P1)
                    .addComponent(Piz1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P2)
                    .addComponent(Piz2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel12)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P3)
                    .addComponent(Piz3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P4)
                    .addComponent(Piz4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addGap(26, 26, 26)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P5)
                    .addComponent(Piz5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Pizzas", jPanel6);

        A1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        A1.setText("Buffalo Tradicional ");
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel16.setText("Alitas fritas, salsa picante estilo buffalo");

        A2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        A2.setText("Alitas BBQ ");
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel17.setText("Alitas con salsa BBQ dulce");

        A3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        A3.setText("Alitas Mango Habanero ");
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel18.setText("Salsa de mango con habanero");

        A4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        A4.setText("Alitas Parmesano y Ajo ");
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel19.setText("Salsa de mantequilla, ajo y queso parmesano");

        A5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        A5.setText("Alitas Lemon Pepper ");
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel20.setText("Limón, pimienta, mantequilla");

        Ali1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ali1KeyTyped(evt);
            }
        });

        Ali2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ali2KeyTyped(evt);
            }
        });

        Ali3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ali3KeyTyped(evt);
            }
        });

        Ali4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ali4KeyTyped(evt);
            }
        });

        Ali5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Ali5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(A1)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A3)
                            .addComponent(A4)
                            .addComponent(A5)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel20)))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel16)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 275, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ali1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ali2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ali3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ali4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ali5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A1)
                    .addComponent(Ali1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A2)
                    .addComponent(Ali2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel17)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A3)
                    .addComponent(Ali3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel18)
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A4)
                    .addComponent(Ali4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addGap(26, 26, 26)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A5)
                    .addComponent(Ali5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Alitas", jPanel7);

        B1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        B1.setText("Refresco en lata ");
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel21.setText("Ejemplo: Coca-Cola, Sprite, Fanta");

        B2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        B2.setText("Limonada Natural ");
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel22.setText("Limón, agua, azúcar, hielo");

        B3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        B3.setText("Agua de Horchata ");
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel23.setText("Arroz, leche, vainilla, canela, azúcar");

        B4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        B4.setText("Smoothie de Fresa y Plátano ");
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });

        B5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        B5.setText("Té Helado Natural ");
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel24.setText("Té negro, limón, azúcar");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel25.setText("Fresa, plátano, yogur natural, hielos");

        Bebi1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bebi1KeyTyped(evt);
            }
        });

        Bebi2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bebi2KeyTyped(evt);
            }
        });

        Bebi3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bebi3KeyTyped(evt);
            }
        });

        Bebi4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bebi4KeyTyped(evt);
            }
        });

        Bebi5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Bebi5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(B1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(B2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(B3)
                            .addComponent(B4)
                            .addComponent(B5)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel24)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel21)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 290, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Bebi1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bebi2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bebi3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bebi4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Bebi5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B1)
                    .addComponent(Bebi1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addGap(20, 20, 20)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B2)
                    .addComponent(Bebi2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B3)
                    .addComponent(Bebi3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel23)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B4)
                    .addComponent(Bebi4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addGap(26, 26, 26)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(B5)
                    .addComponent(Bebi5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Bebidas", jPanel3);

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel26.setText("Chocolate, harina, mantequilla, nuez");

        Ps1.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Ps1.setText("Brownie de Chocolate ");
        Ps1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ps1ActionPerformed(evt);
            }
        });

        Ps2.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Ps2.setText("Pastel de Tres Leches ");
        Ps2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ps2ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel27.setText("Bizcocho, leche condensada, evaporada y crema, chantilly");

        Ps3.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Ps3.setText("Galletas de Avena y Pasas ");
        Ps3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ps3ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel28.setText("Avena, harina, pasas, azúcar morena");

        Ps4.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Ps4.setText("Pay de Limón");
        Ps4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ps4ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel29.setText("Base de galleta, crema de limón, leche condensada, limón");

        Ps5.setFont(new java.awt.Font("Sylfaen", 0, 18)); // NOI18N
        Ps5.setText("Helado Artesanal ");
        Ps5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Ps5ActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel30.setText("Ejemplo: Vainilla, chocolate, mango");

        Postre1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Postre1KeyTyped(evt);
            }
        });

        Postre2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Postre2KeyTyped(evt);
            }
        });

        Postre3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Postre3KeyTyped(evt);
            }
        });

        Postre4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Postre4KeyTyped(evt);
            }
        });

        Postre5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                Postre5KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Ps1)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Ps2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Ps3)
                            .addComponent(Ps4)
                            .addComponent(Ps5)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27)
                                    .addComponent(jLabel28)
                                    .addComponent(jLabel29)
                                    .addComponent(jLabel30)))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel26)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Postre1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postre2, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postre3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postre4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Postre5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ps1)
                    .addComponent(Postre1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addGap(20, 20, 20)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ps2)
                    .addComponent(Postre2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jLabel27)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ps3)
                    .addComponent(Postre3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(jLabel28)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ps4)
                    .addComponent(Postre4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addGap(26, 26, 26)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Ps5)
                    .addComponent(Postre5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Postre", jPanel8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void h4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h4ActionPerformed
        if (h4.isSelected()) {
            Hambur4.setEnabled(true);
        } else {
            Hambur4.setEnabled(false);
        }
    }//GEN-LAST:event_h4ActionPerformed

    private void h5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h5ActionPerformed
        if (h5.isSelected()) {
            Hambur5.setEnabled(true);
        } else {
            Hambur5.setEnabled(false);
        }
    }//GEN-LAST:event_h5ActionPerformed

    private void h1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h1ActionPerformed
        if (h1.isSelected()) {
            Hambur1.setEnabled(true);
        } else {
            Hambur1.setEnabled(false);
        }
    }//GEN-LAST:event_h1ActionPerformed

    private void h2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h2ActionPerformed
        if (h2.isSelected()) {
            Hambur2.setEnabled(true);
        } else {
            Hambur2.setEnabled(false);
        }
    }//GEN-LAST:event_h2ActionPerformed

    private void h3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_h3ActionPerformed
        if (h3.isSelected()) {
            Hambur3.setEnabled(true);
        } else {
            Hambur3.setEnabled(false);
        }
    }//GEN-LAST:event_h3ActionPerformed

    private void Hambur1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hambur1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Hambur1KeyTyped

    private void Hambur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hambur2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hambur2ActionPerformed

    private void Hambur2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hambur2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Hambur2KeyTyped

    private void Hambur3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hambur3KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Hambur3KeyTyped

    private void Hambur4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hambur4KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Hambur4KeyTyped

    private void Hambur5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hambur5ActionPerformed

    }//GEN-LAST:event_Hambur5ActionPerformed

    private void Hambur5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Hambur5KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Hambur5KeyTyped

    private void ho1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ho1ActionPerformed
        if (ho1.isSelected()) {
            hot1.setEnabled(true);
        } else {
            hot1.setEnabled(false);
        }
    }//GEN-LAST:event_ho1ActionPerformed

    private void ho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ho2ActionPerformed
        if (ho2.isSelected()) {
            hot2.setEnabled(true);
        } else {
            hot2.setEnabled(false);
        }
    }//GEN-LAST:event_ho2ActionPerformed

    private void ho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ho3ActionPerformed
        if (ho3.isSelected()) {
            hot3.setEnabled(true);
        } else {
            hot3.setEnabled(false);
        }
    }//GEN-LAST:event_ho3ActionPerformed

    private void ho4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ho4ActionPerformed
        if (ho4.isSelected()) {
            hot4.setEnabled(true);
        } else {
            hot4.setEnabled(false);
        }
    }//GEN-LAST:event_ho4ActionPerformed

    private void ho5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ho5ActionPerformed
        if (ho5.isSelected()) {
            hot5.setEnabled(true);
        } else {
            hot5.setEnabled(false);
        }
    }//GEN-LAST:event_ho5ActionPerformed

    private void Hambur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Hambur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Hambur1ActionPerformed

    private void hot1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hot1KeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_hot1KeyTyped

    private void hot2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hot2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_hot2KeyTyped

    private void hot3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hot3KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_hot3KeyTyped

    private void hot4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hot4KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_hot4KeyTyped

    private void hot5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_hot5KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_hot5KeyTyped

    private void P1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P1ActionPerformed
       if (P1.isSelected()) {
            Piz1.setEnabled(true);
        } else {
            Piz1.setEnabled(false);
        }
    }//GEN-LAST:event_P1ActionPerformed

    private void P2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P2ActionPerformed
        if (P2.isSelected()) {
            Piz2.setEnabled(true);
        } else {
            Piz2.setEnabled(false);
        }
    }//GEN-LAST:event_P2ActionPerformed

    private void P3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P3ActionPerformed
        if (P3.isSelected()) {
            Piz3.setEnabled(true);
        } else {
            Piz3.setEnabled(false);
        }
    }//GEN-LAST:event_P3ActionPerformed

    private void P4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P4ActionPerformed
        if (P4.isSelected()) {
            Piz4.setEnabled(true);
        } else {
            Piz4.setEnabled(false);
        }
    }//GEN-LAST:event_P4ActionPerformed

    private void P5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_P5ActionPerformed
        if (P5.isSelected()) {
            Piz5.setEnabled(true);
        } else {
            Piz5.setEnabled(false);
        }
    }//GEN-LAST:event_P5ActionPerformed

    private void Piz1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Piz1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Piz1KeyTyped

    private void Piz2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Piz2KeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Piz2KeyTyped

    private void Piz3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Piz3KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Piz3KeyTyped

    private void Piz4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Piz4KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Piz4KeyTyped

    private void Piz5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Piz5KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Piz5KeyTyped

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        if (A5.isSelected()) {
            Ali5.setEnabled(true);
        } else {
            Ali5.setEnabled(false);
        }
    }//GEN-LAST:event_A5ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        if (A4.isSelected()) {
            Ali4.setEnabled(true);
        } else {
            Ali4.setEnabled(false);
        }
    }//GEN-LAST:event_A4ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        if (A3.isSelected()) {
            Ali3.setEnabled(true);
        } else {
            Ali3.setEnabled(false);
        }
    }//GEN-LAST:event_A3ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        if (A2.isSelected()) {
            Ali2.setEnabled(true);
        } else {
            Ali2.setEnabled(false);
        }
    }//GEN-LAST:event_A2ActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        if (A1.isSelected()) {
            Ali1.setEnabled(true);
        } else {
            Ali1.setEnabled(false);
        }
    }//GEN-LAST:event_A1ActionPerformed

    private void Ali1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ali1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Ali1KeyTyped

    private void Ali2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ali2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Ali2KeyTyped

    private void Ali3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ali3KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Ali3KeyTyped

    private void Ali4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ali4KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Ali4KeyTyped

    private void Ali5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Ali5KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Ali5KeyTyped

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
         if (B1.isSelected()) {
            Bebi1.setEnabled(true);
        } else {
            Bebi1.setEnabled(false);
        }
    }//GEN-LAST:event_B1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        if (B2.isSelected()) {
            Bebi2.setEnabled(true);
        } else {
            Bebi2.setEnabled(false);
        }
    }//GEN-LAST:event_B2ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        if (B3.isSelected()) {
            Bebi3.setEnabled(true);
        } else {
            Bebi3.setEnabled(false);
        }
    }//GEN-LAST:event_B3ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        if (B4.isSelected()) {
            Bebi4.setEnabled(true);
        } else {
            Bebi4.setEnabled(false);
        }
    }//GEN-LAST:event_B4ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        if (B5.isSelected()) {
            Bebi5.setEnabled(true);
        } else {
            Bebi5.setEnabled(false);
        }
    }//GEN-LAST:event_B5ActionPerformed

    private void Bebi1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bebi1KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Bebi1KeyTyped

    private void Bebi2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bebi2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Bebi2KeyTyped

    private void Bebi3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bebi3KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Bebi3KeyTyped

    private void Bebi4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bebi4KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Bebi4KeyTyped

    private void Bebi5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Bebi5KeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Bebi5KeyTyped

    private void Ps1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ps1ActionPerformed
        if (Ps1.isSelected()) {
            Postre1.setEnabled(true);
        } else {
            Postre1.setEnabled(false);
        }
    }//GEN-LAST:event_Ps1ActionPerformed

    private void Ps2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ps2ActionPerformed
        if (Ps2.isSelected()) {
            Postre2.setEnabled(true);
        } else {
            Postre2.setEnabled(false);
        }
    }//GEN-LAST:event_Ps2ActionPerformed

    private void Ps3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ps3ActionPerformed
        if (Ps3.isSelected()) {
            Postre3.setEnabled(true);
        } else {
            Postre3.setEnabled(false);
        }
    }//GEN-LAST:event_Ps3ActionPerformed

    private void Ps4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ps4ActionPerformed
       if (Ps4.isSelected()) {
            Postre4.setEnabled(true);
        } else {
            Postre4.setEnabled(false);
        }
    }//GEN-LAST:event_Ps4ActionPerformed

    private void Ps5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Ps5ActionPerformed
        if (Ps5.isSelected()) {
            Postre5.setEnabled(true);
        } else {
            Postre5.setEnabled(false);
        }
    }//GEN-LAST:event_Ps5ActionPerformed

    private void Postre1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Postre1KeyTyped
       char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Postre1KeyTyped

    private void Postre2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Postre2KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Postre2KeyTyped

    private void Postre3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Postre3KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Postre3KeyTyped

    private void Postre4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Postre4KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Postre4KeyTyped

    private void Postre5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Postre5KeyTyped
        char c = evt.getKeyChar();
        if (!Character.isDigit(c)) {
            evt.consume();
        }
    }//GEN-LAST:event_Postre5KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menuu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menuu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox A1;
    private javax.swing.JCheckBox A2;
    private javax.swing.JCheckBox A3;
    private javax.swing.JCheckBox A4;
    private javax.swing.JCheckBox A5;
    private javax.swing.JTextField Ali1;
    private javax.swing.JTextField Ali2;
    private javax.swing.JTextField Ali3;
    private javax.swing.JTextField Ali4;
    private javax.swing.JTextField Ali5;
    private javax.swing.JCheckBox B1;
    private javax.swing.JCheckBox B2;
    private javax.swing.JCheckBox B3;
    private javax.swing.JCheckBox B4;
    private javax.swing.JCheckBox B5;
    private javax.swing.JTextField Bebi1;
    private javax.swing.JTextField Bebi2;
    private javax.swing.JTextField Bebi3;
    private javax.swing.JTextField Bebi4;
    private javax.swing.JTextField Bebi5;
    private javax.swing.JTextField Hambur1;
    private javax.swing.JTextField Hambur2;
    private javax.swing.JTextField Hambur3;
    private javax.swing.JTextField Hambur4;
    private javax.swing.JTextField Hambur5;
    private javax.swing.JCheckBox P1;
    private javax.swing.JCheckBox P2;
    private javax.swing.JCheckBox P3;
    private javax.swing.JCheckBox P4;
    private javax.swing.JCheckBox P5;
    private javax.swing.JTextField Piz1;
    private javax.swing.JTextField Piz2;
    private javax.swing.JTextField Piz3;
    private javax.swing.JTextField Piz4;
    private javax.swing.JTextField Piz5;
    private javax.swing.JTextField Postre1;
    private javax.swing.JTextField Postre2;
    private javax.swing.JTextField Postre3;
    private javax.swing.JTextField Postre4;
    private javax.swing.JTextField Postre5;
    private javax.swing.JCheckBox Ps1;
    private javax.swing.JCheckBox Ps2;
    private javax.swing.JCheckBox Ps3;
    private javax.swing.JCheckBox Ps4;
    private javax.swing.JCheckBox Ps5;
    private javax.swing.JCheckBox h1;
    private javax.swing.JCheckBox h2;
    private javax.swing.JCheckBox h3;
    private javax.swing.JCheckBox h4;
    private javax.swing.JCheckBox h5;
    private javax.swing.JCheckBox ho1;
    private javax.swing.JCheckBox ho2;
    private javax.swing.JCheckBox ho3;
    private javax.swing.JCheckBox ho4;
    private javax.swing.JCheckBox ho5;
    private javax.swing.JTextField hot1;
    private javax.swing.JTextField hot2;
    private javax.swing.JTextField hot3;
    private javax.swing.JTextField hot4;
    private javax.swing.JTextField hot5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane2;
    // End of variables declaration//GEN-END:variables
}
